
service: mailto-marymakes

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: post
          path: mailto-marymakes
          cors: true

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]